### ISSUE TITLE
Open Source Initiative

### ISSUE THREAD

**Issue by AhmedThahir** [alejandro0619/University-Notes#3]
We have started a progressive web app, where anyone can contributed short and crisp notes.
Would you be interested in contributing?

https://uni-notes.netlify.app/

**Comment by alejandro0619** [comment]
This repo's  was intended to work as a vault, not really a well organized vault, so the content saved here shouldn't be that useful for someone looking up for content to learn from. But anyway I'll your repo a try and see if I can help you somehow.
